

    function translateText() {
    const inputText = document.getElementById('input-text').value;

    if(inputText == ""){
        textoContainer.innerHTML = "";
        return;
    }

    const outputTextElement = document.getElementById('output-text');
    
    // Llamar a la API de traducción de Google Translate
    fetch(`https://translate.googleapis.com/translate_a/single?client=gtx&sl=auto&tl=es&dt=t&q=${encodeURI(inputText)}`)
        .then(response => response.json())
        .then(data => {
            const translatedText = data[0][0][0];
            //outputTextElement.textContent = translatedText;
            // Crear un nuevo div para mostrar el texto obtenido de la API

            var nuevoDiv = document.createElement('div');
            nuevoDiv.className = 'output'
            nuevoDiv.textContent = translatedText;

            // Agregar el nuevo div al contenedor principal
            textoContainer.appendChild(nuevoDiv);
        })
        .catch(error => {
            console.error('Error al traducir:', error);
            outputTextElement.textContent = 'Error al traducir el texto.';
        });

        
}
        //const inputText = document.getElementById('input-text').value;
        //const outputTextElement = document.getElementById('output-text');
    
    
    
    

    const combinacionesEspeciales = {
        'ひれ伏し': 'hirefushi',
        'あなた方': 'anatagata',
        '飛び降り': 'tobiori',
        '道路沿い': 'dourozoi',
        '向こう側': 'mukougawa',
        '憐れみ深': 'awaremibuka',
        '平手打ち': 'hirateuchi',        

        '婚約中': 'kon-yakuchuu',
        '預言者': 'yogensha',
        '祭司長': 'saishichō',
        '統治者': 'tōchisha',
        '注意深': 'chuuibuka',
        '上まで': 'uemade',
        '行って': 'itte',
        '出掛け': 'dekake',
        '止まっ': 'tomat',
        '誘惑者': 'yuuwakusha',
        'しょう': 'shou',
        'はっき': 'hakki',
        '裁判官': 'saibankan',
        '不道徳': 'fudoutoku',
        '徴税人': 'chouzeinin',
        '偽善者': 'gizensha',

        '初め': 'hajime',
        '歴史': 'rekishi',
        '兄弟': 'kyōdai',
        '強制': 'kyōsei',
        '移住': 'ijuu',
        '時期': 'jiki',
        '呼ば': 'yoba',
        '14': 'juuyon',
        '十四': 'juuyon',
        '全部': 'zenbu',
        'った': 'tta',
        '誕生': 'tanjō',
        '経緯': 'keii',
        '母親': 'hahaoya',
        '父親': 'chichioya',
        '2人': 'futari',
        'ニ人': 'futari',
        '結ば': 'musuba',
        '正し': 'tadashi',
        'って': 'tte',
        '妊娠': 'ninshin',
        '離婚': 'rikon',
        '考え': 'kangae',
        '天使': 'tenshi',
        '恐れ': 'osore',
        '彼女': 'kanojo',
        '全て': 'subete',
        '実際': 'jissai',
        '実現': 'jitsugen',
        '処女': 'shojo',
        '意味': 'imi',
        '指示': 'shiji',
        '行い': 'okonai',
        '関係': 'kankei',
        '時代': 'jidai',
        '占星': 'sensei',
        '東方': 'tōhō',
        '律法': 'rippō',
        '集め': 'atsume',
        '書い': 'kai',
        '最も': 'mottomo',
        '足り': 'tari',
        '学者': 'gakusha',
        '人々': 'hitobito',
        '統治': 'toochi',
        '牧者': 'bokusha',
        '呼び': 'yobi',
        '寄せ': 'yose',
        '遣わ': 'tsukawa',
        '報告': 'hookoku',
        '言葉': 'kotoba',
        '何と': 'nanto',
        '行き': 'iki',
        '子供': 'kodomo',
        '非常': 'hijoo',
        '喜ん': 'yoroko-n',
        '入り': 'hairi',
        '幼い': 'osanai',
        '乳香': 'nyuukoo',
        '没薬': 'motsuyaku',
        '出し': 'dashi',
        '警告': 'keikoku',
        '通っ': 'toot',
        '帰っ': 'kaet',
        '与え': 'atae',
        '来て': 'kite',
        '荒野': 'kooya',
        '伝道': 'dendoo',
        '言っ': 'it',
        '改め': 'aratame',
        '近づ': 'chikadzu',
        '整え': 'totonoe',
        '道路': 'dooro',
        '真っ': 'mas',
        '食べ': 'tabe',
        '野生': 'yasei',
        '締め': 'shime',
        'バッ': 'bat',
        '全土': 'zendo',
        '一帯': 'ittai',
        '正直': 'shoojiki',
        '告白': 'kokuhaku',
        '場所': 'basho',
        '大勢': 'oosei',
        '来る': 'kuru',
        '行動': 'koodoo',
        '根元': 'nemoto',
        '立派': 'rippa',
        '切り': 'kiri',
        '投げ': 'nage',
        '込ま': 'koma',
        '施し': 'hodokoshi',
        '脱が': 'nuga',
        '作業': 'sagyoo',
        '使う': 'tsukau',
        'シャ': 'sha',
        '脱穀': 'dakkoku',
        'っか': 'kka',
        '消え': 'kie',
        '焼き': 'yaki',
        '必要': 'hitsuyoo',
        '今回': 'konkai',
        '行う': 'okonau',
        '以上': 'ijou',
        '開き': 'hiraki',
        '下っ': 'kudat',
        '上に': 'ueni',
        '悪魔': 'akuma',
        '誘惑': 'yuuwaku',
        '日間': 'nichikan',
        'っと': 'tto',
        '断食': 'danjiki',
        '空腹': 'kuufuku',
        '命じ': 'meiji',
        '次い': 'tsui',
        '連れ': 'tsure',
        '神殿': 'shinden',
        '立た': 'tata',
        '命令': 'mirei',
        '出す': 'dasu',
        '乗せ': 'nose',
        '運び': 'hakobi',
        '世界': 'sekai',
        '王国': 'oukoku',
        '栄光': 'eikou',
        '崇拝': 'suuhai',
        '離れ': 'hanare',
        '崇拝': 'suuhai',
        '奉仕': 'houshi',
        '神聖': 'shinsei',
        '仕え': 'tsukae',
        '始め': 'hajime',
        '地域': 'chiiki',
        '住ん': 'sun',
        '土地': 'tochi',
        '向こ': 'mukou',
        '覆わ': 'ouware',
        '地方': 'chihou',
        '昇っ': 'nobot',
        '開始': 'kaishi',
        
        //names
        'ア湖': 'ako',
        'イ湖': 'iko',
        'ウ湖': 'uko',
        'エ湖': 'eko',
        'オ湖': 'oko',
        'カ湖': 'kako',
        'キ湖': 'kiko',
        'ク湖': 'kuko',
        'ケ湖': 'keko',
        'コ湖': 'koko',
        'ガ湖': 'gako',
        'ギ湖': 'giko',
        'グ湖': 'guko',
        'ゲ湖': 'geko',
        'ゴ湖': 'goko',
        'サ湖': 'sako',
        'シ湖': 'shiko',
        'ス湖': 'suko',
        'セ湖': 'seko',
        'ソ湖': 'soko',
        'ザ湖': 'zako',
        'ジ湖': 'jiko',
        'ズ湖': 'zuko',
        'ゼ湖': 'zeko',
        'ゾ湖': 'zoko',
        'タ湖': 'tako',
        'チ湖': 'chiko',
        'ツ湖': 'tsuko',
        'テ湖': 'teko',
        'ト湖': 'toko',
        'ダ湖': 'dako',
        'ヂ湖': 'djiko',
        'ヅ湖': 'dzuko',
        'デ湖': 'deko',
        'ド湖': 'doko',
        'ナ湖': 'nako',
        'ニ湖': 'niko',
        'ヌ湖': 'nuko',
        'ネ湖': 'neko',
        'ノ湖': 'noko',
        'ハ湖': 'hako',
        'ヒ湖': 'hiko',
        'フ湖': 'fuko',
        'ホ湖': 'hoko',
        'バ湖': 'bako',
        'ベ湖': 'beko',
        'ビ湖': 'biko',
        'ブ湖': 'buko',
        'ボ湖': 'boko',
        'パ湖': 'pako',
        'ピ湖': 'piko',
        'プ湖': 'puko',
        'ポ湖': 'poko',
        'マ湖': 'mako',
        'ミ湖': 'miko',
        'ム湖': 'muko',
        'メ湖': 'meko',
        'モ湖': 'moko',
        'ヤ湖': 'yako',
        'ユ湖': 'yuko',
        'ヨ湖': 'yoko',
        'ラ湖': 'rako',
        'リ湖': 'riko',
        'ル湖': 'ruko',
        'レ湖': 'reko',
        'ロ湖': 'roko',
        'ン湖': 'nko',
        'ヴ湖': 'vko',
        'ワ湖': 'wako',
        'ヰ湖': 'wiko',
        'ヱ湖': 'weko',
        'ヲ湖': 'woko',
        
        'ヤ中': 'yajuu',
        'ユ中': 'yujuu',
        'ヨ中': 'yojuu',
        'ラ中': 'rajuu',
        'リ中': 'rijuu',
        'ル中': 'rujuu',
        'レ中': 'rejuu',
        'ロ中': 'rojuu',
        'ン中': 'njuu',
        'ヴ中': 'vjuu',
        'ワ中': 'wajuu',
        'ヰ中': 'wijuu',
        'ヱ中': 'wejuu',
        'ヲ中': 'wojuu',
        'ア中': 'ajuu',
        'イ中': 'ijuu',
        'ウ中': 'ujuu',
        'エ中': 'ejuu',
        'オ中': 'ojuu',
        'カ中': 'kajuu',
        'キ中': 'kijuu',
        'ク中': 'kujuu',
        'ケ中': 'kejuu',
        'コ中': 'kojuu',
        'ガ中': 'gajuu',
        'ギ中': 'gijuu',
        'グ中': 'gujuu',
        'ゲ中': 'gejuu',
        'ゴ中': 'gojuu',
        'サ中': 'sajuu',
        'シ中': 'shijuu',
        'ス中': 'sujuu',
        'セ中': 'sejuu',
        'ソ中': 'sojuu',
        'ザ中': 'zajuu',
        'ジ中': 'jijuu',
        'ズ中': 'zujuu',
        'ゼ中': 'zejuu',
        'ゾ中': 'zojuu',
        'タ中': 'tajuu',
        'チ中': 'chijuu',
        'ツ中': 'tsujuu',
        'テ中': 'tejuu',
        'ト中': 'tojuu',
        'ダ中': 'dajuu',
        'ヂ中': 'djijuu',
        'ヅ中': 'dzujuu',
        'デ中': 'dejuu',
        'ド中': 'dojuu',
        'ナ中': 'najuu',
        'ニ中': 'nijuu',
        'ヌ中': 'nujuu',
        'ネ中': 'nejuu',
        'ノ中': 'nojuu',
        'ハ中': 'hajuu',
        'ヒ中': 'hijuu',
        'フ中': 'fujuu',
        'ホ中': 'hojuu',
        'バ中': 'bajuu',
        'ベ中': 'bejuu',
        'ビ中': 'bijuu',
        'ブ中': 'bujuu',
        'ボ中': 'bojuu',
        'パ中': 'pajuu',
        'ピ中': 'pijuu',
        'プ中': 'pujuu',
        'ポ中': 'pojuu',
        'マ中': 'majuu',
        'ミ中': 'mijuu',
        'ム中': 'mujuu',
        'メ中': 'mejuu',
        'モ中': 'mojuu',
        'ヤ中': 'yajuu',
        'ユ中': 'yujuu',
        'ヨ中': 'yojuu',
        'ラ中': 'rajuu',
        'リ中': 'rijuu',
        'ル中': 'rujuu',
        'レ中': 'rejuu',
        'ロ中': 'rojuu',
        'ン中': 'njuu',
        'ヴ中': 'vjuu',
        'ワ中': 'wajuu',
        'ヰ中': 'wijuu',
        'ヱ中': 'wejuu',
        'ヲ中': 'wojuu',

        'ア川': 'agawa',
        'イ川': 'igawa',
        'ウ川': 'ugawa',
        'エ川': 'egawa',
        'オ川': 'ogawa',
        'カ川': 'kagawa',
        'キ川': 'kigawa',
        'ク川': 'kugawa',
        'ケ川': 'kegawa',
        'コ川': 'kogawa',
        'ガ川': 'gagawa',
        'ギ川': 'gigawa',
        'グ川': 'gugawa',
        'ゲ川': 'gegawa',
        'ゴ川': 'gogawa',
        'サ川': 'sagawa',
        'シ川': 'shigawa',
        'ス川': 'sugawa',
        'セ川': 'segawa',
        'ソ川': 'sogawa',
        'ザ川': 'zagawa',
        'ジ川': 'jigawa',
        'ズ川': 'zugawa',
        'ゼ川': 'zegawa',
        'ゾ川': 'zogawa',
        'タ川': 'tagawa',
        'チ川': 'chigawa',
        'ツ川': 'tsugawa',
        'テ川': 'tegawa',
        'ト川': 'togawa',
        'ダ川': 'dagawa',
        'ヂ川': 'djigawa',
        'ヅ川': 'dzugawa',
        'デ川': 'degawa',
        'ド川': 'dogawa',
        'ナ川': 'nagawa',
        'ニ川': 'nigawa',
        'ヌ川': 'nugawa',
        'ネ川': 'negawa',
        'ノ川': 'nogawa',
        'ハ川': 'hagawa',
        'ヒ川': 'higawa',
        'フ川': 'fugawa',
        'ホ川': 'hogawa',
        'バ川': 'bagawa',
        'ベ川': 'begawa',
        'ビ川': 'bigawa',
        'ブ川': 'bugawa',
        'ボ川': 'bogawa',
        'パ川': 'pagawa',
        'ピ川': 'pigawa',
        'プ川': 'pugawa',
        'ポ川': 'pogawa',
        'マ川': 'magawa',
        'ミ川': 'migawa',
        'ム川': 'mugawa',
        'メ川': 'megawa',
        'モ川': 'mogawa',
        'ヤ川': 'yagawa',
        'ユ川': 'yugawa',
        'ヨ川': 'yogawa',
        'ラ川': 'ragawa',
        'リ川': 'rigawa',
        'ル川': 'rugawa',
        'レ川': 'regawa',
        'ロ川': 'rogawa',
        'ン川': 'ngawa',
        'ヴ川': 'vgawa',
        'ワ川': 'wagawa',
        'ヰ川': 'wigawa',
        'ヱ川': 'wegawa',
        'ヲ川': 'wogawa',

        //names
        '岸辺': 'kishibe',
        '歩い': 'arui',
        '漁師': 'ryoushi',
        '直ち': 'tadachi',
        '捨て': 'sute',
        '呼ぶ': 'jobu',
        '残し': 'nokoshi',
        '巡り': 'meguri',
        '会堂': 'kaidou',
        '教え': 'oshie',
        '良い': 'yoi',
        '知ら': 'shira',
        '伝え': 'tsutae',
        '病気': 'byouki',
        '不調': 'fuchou',
        '治し': 'naoshi',
        '評判': 'hyouban',
        '苦痛': 'kutsuu',
        '邪悪': 'jaaku',
        '結果': 'kekka',
        '群衆': 'gunshuu',
        '下ろ': 'oro',
        '弟子': 'deshi',
        '導き': 'michibiki',
        '幸福': 'koufuku',
        '嘆き': 'nageki',
        '悲し': 'kanashi',
        '慰め': 'nagusame',
        '温和': 'onwa',
        '地球': 'chikyuu',
        '切望': 'setsubou',
        '満た': 'mita',
        '憐れ': 'aware',
        '純粋': 'junsui',
        '平和': 'heiwa',
        '迫害': 'hakugai',
        '非難': 'hinan',
        '悪意': 'akui',
        '喜び': 'yorokobi',
        '歓喜': 'kanki',
        '報い': 'mukui',
        '以前': 'izen',
        '同じ': 'onaji',
        '塩気': 'shioke',
        '失っ': 'ushinat',
        '使え': 'tsukae',
        '踏み': 'fumi',
        '隠さ': 'kakusa',
        '覆う': 'ouu',
        '輝か': 'kagayaka',
        '照ら': 'tera',
        '消す': 'kesu',
        '来た': 'kita',
        '文字': 'moji',
        '1つ': 'hitotsu',
        '1画': 'hikaku',
        '早い': 'hayai',
        '記さ': 'shirusa',
        '小さ': 'chiisa',
        '入れ': 'haire',
        '古代': 'kodai',
        '知っ': 'shit',
        '殺人': 'satsujin',
        '犯す': 'okasu',
        '法廷': 'houtei',
        '引き': 'hiki',
        '出さ': 'dasa',
        '仲間': 'nakama',
        '続け': 'tsudzuke',
        '法廷': 'houtei',
        '侮辱': 'bujoku',
        '的な': 'tekina',
        '最高': 'saikou',
        '愚か': 'oroka',
        '燃え': 'moe',
        '供え': 'sonae',
        '祭壇': 'saidan',
        '仲直': 'nakanao',
        '捧げ': 'sasage',
        '訴訟': 'soshou',
        '相手': 'aite',
        '向か': 'muka',
        '素早': 'subaya',
        '問題': 'mondai',
        '解決': 'kaiketsu',
        '引き': 'hiki',
        '渡し': 'watashi',
        '役人': 'yakunin',
        '牢屋': 'rouya',
        '最後': 'saigo',
        '硬貨': 'kouka',
        '終え': 'oe',
        '出ら': 'dera',
        '姦淫':'kanin',
        '女性': 'josei',
        '情欲': 'jouyoku',
        '犯さ': 'okasa',
        '失う': 'ushinau',
        '方が': 'houga',
        '全身': 'zenshin',
        '離し': 'hanashi',
        '証書': 'shousho',
        '性的': 'seiteki',
        '以外': 'igai',
        '理由': 'riyuu',
        '結婚': 'kekkon',
        '誓い': 'chikai',
        '実行': 'jikkou',
        '誓約': 'seiyaku',
        '果た': 'hata',
        '一切': 'issai',
        '誓っ': 'chikat',
        '懸け': 'kake',
        '王座': 'ouza',
        '偉大': 'idai',
        '都市': 'toshi',
        '1本': 'ippon',
        'はい': 'hai',
        '出る': 'deru',
        '悪人': 'akunin',
        '争っ': 'arasot',
        '向け': 'muke',
        '内衣': 'naie',
        '外衣': 'gaii',
        '権威': 'keni',
        '行く': 'iku',
        '要求': 'youkyuu',
        '一緒': 'issho',
        '求め': 'motome',
        '借り': 'kari',
        '隣人': 'rinjin',
        '祈り': 'inori',
        '善人': 'zen-nin',
        '太陽': 'taiyou',
        '昇ら': 'nobora',
        '注目': 'chuumoku',
        '善行': 'zenkou',
        '注意': 'chuui',
        '称賛': 'shouzan',
        '街路': 'gairo',
        '施す': 'hodokusu',
        'ッパ': 'ppa',
        '吹い': 'fui',
        '祈る': 'inoru',
        '立っ': 'tat',
        '好み': 'konomi',
        '部屋': 'heya',
        '入っ': 'hait',
        '閉じ': 'toji',
        '異国': 'ikoku',
        '何度': 'nando',
        '多く': 'ouku',
        '並べ': 'narabe',
        '祈ら': 'inora',
        '来ま': 'kima',
        '望ま': 'nozoma',
        '行わ': 'okonawa',
        '今日': 'kyou',
        '犯し': 'okashi',
        '許し': 'yurushi',
        '陥ら': 'ochiira'




        // Agrega más combinaciones aquí según tus necesidades
    };
    
    const valoresPredeterminados = {
        '初': 'hatsu',
        'め': 'me',
        'に': 'ni',
        'あ': 'a',
        'ア': 'a',
        'い': 'i',
        'イ': 'i',
        '言': 'i',
        '入': 'i',
        'う': 'u',
        'ウ': 'u',
        '産': 'u',
        '生': 'u',
        'え': 'e',
        'エ': 'e',
        'へ': 'e',
        'オ': 'o',
        'お': 'o',
        '起': 'o',
        'か': 'ka',
        'カ': 'ka',
        'き': 'ki',
        'キ': 'ki',
        'く': 'ku',
        'ク': 'ku',
        'け': 'ke',
        'ケ': 'ke',
        'コ': 'ko',
        'ガ': 'ga',
        'ギ': 'gi',
        'グ': 'gu',
        'ゲ': 'ge',
        'ゴ': 'go',
        'サ': 'sa',
        'シ': 'shi',
        'ス': 'su',
        'セ': 'se',
        'ソ': 'so',
        'ザ': 'za',
        'ジ': 'ji',
        'ズ': 'zu',
        'ゼ': 'ze',
        'ゾ': 'zo',
        'タ': 'ta',
        'チ': 'chi',
        'ツ': 'tsu',
        'テ': 'te',
        'ト': 'to',
        'ダ': 'da',
        'ヂ': 'dji',
        'ヅ': 'dzu',
        'デ': 'de',
        'ド': 'do',
        'ナ': 'na',
        'ニ': 'ni',
        'ヌ': 'nu',
        'ネ': 'ne',
        'ノ': 'no',
        'こ': 'ko',
        '子': 'ko',
        'が': 'ga',
        'ぎ': 'gi',
        'ぐ': 'gu',
        'げ': 'ge',
        'ご': 'go',
        'さ': 'sa',
        '覚': 'sa',
        'し': 'shi',
        '師': 'shi',
        'す': 'su',
        'せ': 'se',
        'そ': 'so',
        'ざ': 'za',
        'じ': 'ji',
        'ず': 'zu',
        'ぜ': 'ze',
        'ぞ': 'zo',
        'た': 'ta',
        'ち': 'chi',
        'つ': 'tsu',
        'て': 'te',
        'と': 'to',
        '通': 'to',
        'だ': 'da',
        'ぢ': 'dji',
        'づ': 'dzu',
        '付': 'dzu',
        'で': 'de',
        'ど': 'do',
        'な': 'na',
        '名': 'na',
        'に': 'ni',
        'ぬ': 'nu',
        'ね': 'ne',
        'の': 'no',
        'は': 'wa',
        'ハ': 'ha',
        'ひ': 'hi',
        'ヒ': 'hi',
        'ふ': 'fu',
        'フ': 'fu',
        'ヘ': 'he',
        'ほ': 'ho',
        'ホ': 'ho',
        'ば': 'ba',
        'バ': 'ba',
        'び': 'bi',
        'ビ': 'bi',
        'ぶ': 'bu',
        'ブ': 'bu',
        'べ': 'be',
        'ベ': 'be',
        'ぼ': 'bo',
        'ボ': 'bo',
        'ぱ': 'pa',
        'パ': 'pa',
        'ぴ': 'pi',
        'ピ': 'pi',
        'ぷ': 'pu',
        'プ': 'pu',
        'ペ': 'pe',
        'ぽ': 'po',
        'ポ': 'po',
        'ま': 'ma',
        'マ': 'ma',
        'み': 'mi',
        'ミ': 'mi',
        '見': 'mi',
        'む': 'mu',
        'ム': 'mu',
        'め': 'me',
        'メ': 'me',
        'も': 'mo',
        'モ': 'mo',
        '持': 'mo',
        'や': 'ya',
        'ヤ': 'ya',
        'ゆ': 'yu',
        'ユ': 'yu',
        'よ': 'yo',
        'ヨ': 'yo',
        'ら': 'ra',
        'ラ': 'ra',
        'り': 'ri',
        'リ': 'ri',
        'る': 'ru',
        'ル': 'ru',
        'れ': 're',
        'レ': 're',
        'ろ': 'ro',
        'ロ': 'ro',
        'ん': 'n',
        'ン': 'n',
        'ヴ': 'v',
        'を': 'wo',
        'わ': 'wa',
        'ワ': 'wa',
        'ヰ': 'wi',
        'ヱ': 'we',
        'ヲ': 'wo',
        '書': 'sho',
        '王': 'ō',
        '妻': 'tsuma',
        '後': 'ato',
        '代': 'dai',
        '前': 'mae',
        '聖': 'sei',
        '性': 'sei',
        '力': 'chikara',
        '夫': 'otto',
        '人': 'hito',
        '恥': 'haji',
        '思': 'omo',
        '夢': 'yume',
        '中': 'naka',
        '現': 'arawa',
        '迎': 'muka',
        '恐': 'osore',
        '男': 'otoko',
        '民': 'tami',
        '罪': 'tsumi',
        '救': 'suku',
        '語': 'kata',
        '方': 'kata',
        '訳': 'yaku',
        '私': 'watashi',
        '共': 'tomo',
        '神': 'kami',
        '眠': 'nemu',
        '通': 'tō',
        '時': 'toki',
        '術': 'jutsu',
        '来': 'rai',
        '星': 'hoshi',
        '聞': 'ki',
        '動': 'dō',
        '揺': 'yō',
        '民': 'tami',
        '学': 'gaku',
        '全': 'zen',
        '員': 'in',
        '尋': 'tazu',
        '答': 'kota',
        '決': 'kes',
        '取': 'to',
        '町': 'machi',
        '者': 'mono',
        '出': 'shutsu',
        '敬': 'kei',
        '意': 'i',
        '表': 'hyoo',
        '皆': 'mina',
        '間': 'ma',
        '際': 'sai',
        '捜': 'saga',
        '先': 'saki',
        '所': 'tokoro',
        '家': 'ie',
        '金': 'kin',
        '贈': 'oku',
        '物': 'mono',
        '差': 'sa',
        '戻': 'modo',
        '自': 'ji',
        '分': 'bu-n',
        '国': 'kuni',
        '別': 'betsu',
        '道': 'michi',
        '悔': 'ku',
        '天': 'ten',
        '叫': 'sake',
        '声':'koe',
        '毛': 'ke',
        '服': 'fuku',
        '着': 'gi',
        '腰': 'koshi',
        '革': 'kawa',
        '帯': 'obi',
        '蜂': 'hachi',
        '蜜': 'mitsu',
        '頃': 'goro',
        '川': 'kawa',
        '受': 'u',
        '派': 'ha',
        '毒': 'doku',
        '蛇': 'hebi',
        '憤': 'ikidoo',
        '逃': 'noga',
        '誰': 'dare',
        '示': 'shime',
        '父': 'chichi',
        '心': 'kokoro',
        '石': 'ishi',
        '木': 'ki',
        '置': 'o',
        '実': 'mi',
        '倒': 'tao',
        '火': 'hi',
        '水':'mizu',
        '強': 'tsuyo',
        '値': 'atai',
        '農': 'noo',
        '手': 'te',
        '場': 'ba',
        '小': 'ko',
        '麦': 'mugi',
        '倉': 'kura',
        '殻': 'kara',
        '払': 'hara',
        '上': 'a',
        '愛': 'ai',
        '導 ': 'michibi',
        '感': 'kan',
        '口': 'kuchi',
        '都': 'miyako',
        '高': 'taka',
        '足': 'ashi',
        '試': 'tame',
        '山': 'yama',
        '去': 'sa',
        '捕': 'to',
        '湖': 'mizuumi',
        '次': 'tsugi',
        '異': 'i',
        '闇': 'yami',
        '大': 'ou',
        '光': 'hikari',
        '死': 'shi',
        '陰': 'kage',
        '影': 'kage',
        '海': 'umi',
        '網': 'ami',
        '魚': 'sakana',
        '従': 'shitaga',
        '目': 'me',
        '舟': 'fune',
        '広': 'hiro',
        '抱': 'kaka',
        '体': 'karada',
        '登': 'tou',
        '地': 'ji',
        '塩': 'shio',
        '何': 'nani',
        '外': 'soto',
        '世': 'yo',
        '籠': 'kago',
        '台': 'dai',
        '破': 'yabu',
        '守': 'mamo',
        '対': 'tai',
        '抱': 'ida',
        '反': 'han',
        '右': 'migi',
        '一': 'ichi',
        '部': 'bu',
        '落': 'ochi',
        '頭': 'atama',
        '髪': 'kami',
        '白': 'shiro',
        '黒': 'kuro',
        '歯': 'ha',
        '頰': 'hoo',
        '背': 'se',
        '敵': 'teki',
        '憎': 'niku',
        '雨': 'ame',
        '降': 'fu',
        '特': 'toku',
        '完': 'kanzen',
        '得': 'e',
        '左': 'hidari',
        '角': 'kado',
        '戸': 'to',
        '日': 'hi'

        
        // ... añade más valores predeterminados aquí
    };
    
    function convertir() {

        const inputValue = document.getElementById('input-text').value;
        // Obtener el contenedor para el resultado del texto ingresado
        var textoContainer = document.getElementById('textoContainer');

              // Limpiar el contenido anterior del contenedor de texto
       // textoContainer.innerHTML = '';

        var inputKanji = '';
        var outputValue = '';
        var i = 0;

        while (i < inputValue.length) {
            let substr2 = inputValue.substr(i, 2); // Obtener los próximos 2 caracteres
            let substr3 = inputValue.substr(i, 3); // Obtener los próximos 3 caracteres
            let substr4 = inputValue.substr(i, 4); // Obtener los próximos 4 caracteres

            let valorEspecial = combinacionesEspeciales[substr4];
            
            

            
    
            if (valorEspecial) {
                outputValue += valorEspecial +' ';
                inputKanji += substr4 +' ';
                // Crear un nuevo div para mostrar el carácter y su valor
                var outputContainer = document.createElement('div');
                outputContainer.className = 'output';
                // Crear un nuevo div para mostrar el carácter
                var caracterDiv = document.createElement('div');
                caracterDiv.className = 'output';
                caracterDiv.textContent = substr4;
                
                // Crear un nuevo div para mostrar el valor del carácter
                var valorDiv = document.createElement('div');
                valorDiv.className = 'output';
                valorDiv.textContent = valorEspecial;

                // Agregar los nuevos divs al contenedor principal
                outputContainer.appendChild(caracterDiv);
                outputContainer.appendChild(valorDiv);
                textoContainer.appendChild(outputContainer);
                i += 4; // Saltar cuatro caracteres en la entrada

                } else if (combinacionesEspeciales[substr3]) {
                    outputValue += combinacionesEspeciales[substr3] +' ';
                    inputKanji += substr3 +' ';
                    // Crear un nuevo div para mostrar el carácter y su valor
                    var outputContainer = document.createElement('div');
                    outputContainer.className = 'output';
                // Crear un nuevo div para mostrar el carácter
                    var caracterDiv = document.createElement('div');
                    caracterDiv.className = 'output';
                    caracterDiv.textContent = substr3;
                
                // Crear un nuevo div para mostrar el valor del carácter
                    var valorDiv = document.createElement('div');
                    valorDiv.className = 'output';
                    valorDiv.textContent = combinacionesEspeciales[substr3];

                // Agregar los nuevos divs al contenedor principal
                    outputContainer.appendChild(caracterDiv);
                    outputContainer.appendChild(valorDiv);
                    textoContainer.appendChild(outputContainer);

                    i += 3; // Saltar tres caracteres en la entrada 
                } else if (combinacionesEspeciales[substr2]) {
                    outputValue += combinacionesEspeciales[substr2];
                    inputKanji += substr2;
                    // Crear un nuevo div para mostrar el carácter y su valor
                    var outputContainer = document.createElement('div');
                    outputContainer.className = 'output';
                // Crear un nuevo div para mostrar el carácter
                    var caracterDiv = document.createElement('div');
                    caracterDiv.className = 'output';
                    caracterDiv.textContent = substr2;
                
                // Crear un nuevo div para mostrar el valor del carácter
                    var valorDiv = document.createElement('div');
                    valorDiv.className = 'output';
                    valorDiv.textContent = combinacionesEspeciales[substr2];

                // Agregar los nuevos divs al contenedor principal
                    outputContainer.appendChild(caracterDiv);
                    outputContainer.appendChild(valorDiv);
                    textoContainer.appendChild(outputContainer);

                    i += 2; // Saltar dos caracteres en la entrada 
                } else {
                    let currentChar = inputValue[i];
                    if (currentChar in valoresPredeterminados) {
                        outputValue += valoresPredeterminados[currentChar] +' ';
                        inputKanji += currentChar +' ';
                        // Crear un nuevo div para mostrar el carácter y su valor
                        var outputContainer = document.createElement('div');
                        outputContainer.className = 'output';
                        // Crear un nuevo div para mostrar el carácter
                        var caracterDiv = document.createElement('div');
                        caracterDiv.className = 'output';
                        caracterDiv.textContent = currentChar;
                // Crear un nuevo div para mostrar el valor del carácter
                        var valorDiv = document.createElement('div');
                        valorDiv.className = 'output';
                        valorDiv.textContent = valoresPredeterminados[currentChar];
                        
                        outputContainer.appendChild(caracterDiv);
                        outputContainer.appendChild(valorDiv);
                        textoContainer.appendChild(outputContainer);
                
                    } else {
                        outputValue += ' ' + currentChar + ' ';
                        inputKanji += currentChar +' ';
                        // Crear un nuevo div para mostrar el carácter y su valor
                        var outputContainer = document.createElement('div');
                        outputContainer.className = 'output';
                        // Crear un nuevo div para mostrar el carácter
                        var caracterDiv = document.createElement('div');
                        caracterDiv.className = 'output';
                        caracterDiv.textContent = currentChar;
                // Crear un nuevo div para mostrar el valor del carácter
                        var valorDiv = document.createElement('div');
                        valorDiv.className = 'output';
                        valorDiv.textContent = currentChar;
                        outputContainer.appendChild(caracterDiv);
                        outputContainer.appendChild(valorDiv);
                        textoContainer.appendChild(outputContainer);
                    }
                    i++;
                }
                
            }

            
            
            
            //document.getElementById('output-value').textContent = outputValue;
            //document.getElementById('output-kanjis').textContent = inputKanji;
        }
    
        

    function execute() {
        translateText();
        convertir();  
    }

    //<div class="output" id="output-text" name="output-text"></div>
      //      <div class="output" id="output-kanjis" name="output-kanjis"></div>
        //    <div class="output" id="output-value" name="output-value"></div>